### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by pingothedoer** [nishant-git/pjsua2#1]
Whenever I run this app, m getting this error:

```

E/art: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                    Process: org.pjsip.pjsua2.app, PID: 14997
                    java.lang.UnsatisfiedLinkError: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
                      at org.pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
                      at org.pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2398)
                      at org.pjsip.pjsua2.pjsua2JNI.new_Endpoint(Native Method)
                      at org.pjsip.pjsua2.Endpoint.<init>(Endpoint.java:68)
                      at org.pjsip.pjsua2.app.MyApp.<clinit>(MyApp.java:296)
                      at org.pjsip.pjsua2.app.MainActivity.onCreate(MainActivity.java:92)
                      at android.app.Activity.performCreate(Activity.java:6500)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
                      at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:6837)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```

**Comment by pookie13** [comment]
i am getting same error please let we all know how to resolve this error.

**Comment by michael-networking** [comment]
same error here. I use latest ndk r12b and pjsip 2.5.1.

**Comment by JesperMajland** [comment]
Me too, any solution?
